name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruby_2-5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.5'
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile
        exclude:
          - gemfile: rails.gemfile
            ruby: '2.5'

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.2.9'
        bundler-cache: true

    - name: Build and test
      run: |
        bundle exec rake

  ruby_2-6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6'
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile
        exclude:
          - gemfile: rails.gemfile
            ruby: '2.6'

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.2.9'
        bundler-cache: true

    - name: Build and test
      run: |
        bundle exec rake
  ruby_2-7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7'
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.2.9'
        bundler-cache: true

    - name: Build and test
      run: |
        bundle exec rake

  ruby_3-0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile
        exclude:
          - gemfile: rails5.2.gemfile
            ruby: '3.0'

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.2.9'
        bundler-cache: true

    - name: Build and test
      run: |
        bundle exec rake

  jruby_9-2-14-0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 'jruby-9.2.14.0'
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile
        exclude:
          - gemfile: rails.gemfile
            ruby: 'jruby-9.2.14.0'
          - gemfile: rails5.2.gemfile
            ruby: 'jruby-9.2.14.0'

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.2.9'
        bundler-cache: true

    - name: Build and test
      run: |
        bundle exec rake spec:integrations spec:units

