name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x
          - 2.7.x
          - 3.0.x
        gemfile:
          - binding_of_caller.gemfile
          - delayed_job.gemfile
          - rack.gemfile
          - rack_1.gemfile
          - rails.gemfile
          - rails5.2.gemfile
          - rails6.0.gemfile
          - resque.gemfile
          - sinatra.gemfile
          - sinatra_1.gemfile
          - standalone.gemfile
        exclude:
          - gemfile: rails.gemfile
            ruby: 2.5.x
          - gemfile: rails.gemfile
            ruby: 2.6.x
          - gemfile: rails5.2.gemfile
            ruby: 3.0.x
    steps:
    - uses: actions/checkout@v1
    
    - name: Install SQLite shared library
      run: |
        sudo apt-get -yqq install libsqlite3-dev

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build and test
      env:
        GEMFILE: ${{ matrix.gemfile }}
      run: |
        bundle exec rake
